---
title: "DSII_homework2"
author: "Chirag Shah"
date: '2019-03-19'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(caret)
library(glmnet)
library(splines)
```

Data Import 

```{r}
concrete = read_csv("concrete.csv") %>%
  janitor::clean_names()
```

#Part A

```{r, fig.height=5}
# matrix of predictors 
x <- model.matrix(compressive_strength~.,concrete)[,-1]
# vector of response
y <- concrete$compressive_strength
theme1 <- trellis.par.get()
theme1$plot.symbol$col <- rgb(.2, .4, .2, .5)
theme1$plot.symbol$pch <- 16
theme1$plot.line$col <- rgb(.8, .1, .1, 1)
theme1$plot.line$lwd <- 2
theme1$strip.background$col <- rgb(.0, .2, .6, .2)
trellis.par.set(theme1)
featurePlot(x, y, plot = "scatter", labels = c("","compressive strength"),
            type = c("p"), layout = c(4, 2))
```


#Part B

```{r}
#polynomial regression
fit1 <- lm(compressive_strength~water, data = concrete)
fit2 <- lm(compressive_strength~poly(water,2), data = concrete) 
fit3 <- lm(compressive_strength~poly(water,3), data = concrete) 
fit4 <- lm(compressive_strength~poly(water,4), data = concrete) 
```

```{r}
#cross validation to determine polynomial degree
set.seed(123)
cv <- cv.glmnet(x, y,
                alpha = 0,
                lambda = exp(seq(1, 4, length = 100)),
                type.measure = "mse")

plot(cv)
```

Because the ISE...

```{r}
anova(fit1,fit2,fit3,fit4) 

plot1 <- ggplot(data = concrete, aes(x = water, y = compressive_strength)) +
     geom_point(color = rgb(.2, .4, .2, .5))
plot1
plot(fit1) + 
plot(fit2) + 
plot(fit3) +
plot(fit4) 
```

#Part C

```{r}
#Generating Test Data
waterlims <- range(concrete$water)
water.grid <- seq(from=waterlims[1], to = waterlims[2])
#fit 1
fit.ss1 <- smooth.spline(concrete$water, concrete$compressive_strength, df = 50)
fit.ss1
pred.ss1 <- predict(fit.ss1, x = water.grid)
pred.ss.df1 <- data.frame(pred = pred.ss1$y, water = water.grid)
#fit 2
fit.ss2 <- smooth.spline(concrete$water, concrete$compressive_strength, df = 60)
fit.ss2
pred.ss2 <- predict(fit.ss2, x = water.grid)
pred.ss.df2 <- data.frame(pred = pred.ss2$y, water = water.grid)
#fit 3
fit.ss3 <- smooth.spline(concrete$water, concrete$compressive_strength, df = 70)
fit.ss3
pred.ss3 <- predict(fit.ss3, x = water.grid)
pred.ss.df3 <- data.frame(pred = pred.ss3$y, water = water.grid)
#cv fit
fit.ss <- smooth.spline(concrete$water, concrete$compressive_strength)
fit.ss
pred.ss <- predict(fit.ss, x = water.grid)
pred.ss.df <- data.frame(pred = pred.ss$y, water = water.grid)
#plot of fits
smooth_fits <- plot1 + geom_line(aes(x = water, y = pred), data = pred.ss.df1,
          color = rgb(.8, .1, .1, 1)) + 
  geom_line(aes(x = water, y = pred), data = pred.ss.df2,
          color = rgb(0, 0, 1, 1)) + 
  geom_line(aes(x = water, y = pred), data = pred.ss.df3,
          color = rgb(1, 0, 1, 1)) + 
  geom_line(aes(x = water, y = pred), data = pred.ss.df,
          color = rgb(.2, .2, .4, 1)) + 
  theme_bw()
smooth_fits
```

###(d) Fit a GAM using all the predictors. Plot the results and explain your findings.
```{r}
library(mgcv)
gam.m1 <- gam(compressive_strength ~ cement + blast_furnace_slag + fly_ash + water + superplasticizer + coarse_aggregate + fine_aggregate + age, data = concrete)
gam.m2 <- gam(compressive_strength ~ cement + blast_furnace_slag + fly_ash + s(water) + superplasticizer + coarse_aggregate + fine_aggregate + age, data = concrete)
anova(gam.m1, gam.m2, test = "F")
plot(gam.m2)
vis.gam(gam.m2, view = c("water", "fly_ash"), 
        plot.type = "contour", color = "topo")
vis.gam(gam.m2, view = c("fine_aggregate","coarse_aggregate"), 
        plot.type = "contour", color = "topo")
```